onboarding:
  - "environments/**"
  - "environments-networks/**"

documentation:
  - "source/**"
  - "architecture-decision-record/**"

dependencies:
  - "terraform/**/*.lock.hcl"

github-workflow:
  - "github/workflows/**"

networking:
  - "terraform/environments/core-vpc/**"
  - "terraform/environments/core-network-services/**"
  - "cidr-allocation.md"

core:
  - "terraform/environments/core-*/**"

security:
  - "terraform/environments/core-security/**"

testing:
  - "policies/**"
