name: Add issues to the project
on:
  issues:
    types:
      - opened

permissions: {}

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@4756e6330fe1e0a736690d3cfd9f11c9399c2ed4 # v0.4.1
        with:
          project-url: https://github.com/orgs/ministryofjustice/projects/17
          github-token: ${{ secrets.TERRAFORM_GITHUB_TOKEN }}
