---
name: core-network-services-deployment

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/environments/core-network-services/**'
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_IN_AUTOMATION: true

defaults:
  run:
    shell: bash

jobs:
  core-network-services-deployment-plan:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1.3.2
      - name: Run terraform plan in terraform/environments
        run: |
          scripts/terraform-init.sh terraform/environments/core-network-services
          PLAN-DETAILS=`scripts/terraform-plan.sh terraform/environments/core-network-services`
          scripts/update-pr-comments.sh ${PLAN-DETAILS}
        env:
          SECRET: ${GITHUB_TOKEN}
          GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}

  core-network-services-deployment-real-apply:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == 'true' }}
    needs: [core-network-services-deployment-plan]
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1.3.2
      - name: Terraform apply
        run: |
          # PLAN ONLY FOR TESTING PURPOSES
          scripts/terraform-init.sh terraform/environments/core-network-services
          scripts/terraform_plan_comment_update.sh terraform/environments/core-network-services

          # scripts/terraform-plan.sh terraform/environments/core-network-services
        env:
          SECRET: ${GITHUB_TOKEN}
          GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}

