name: terraform

on:
  push:
    paths:
      - 'environments/**.json'
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_IN_AUTOMATION: true

jobs:
  create-accounts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.1
      - name: Run scripts/create-accounts.sh
        run: sh scripts/create-accounts.sh
