name: "Terraform: modernisation-platform-account"

on:
  push:
    paths:
      - 'terraform/modernisation-platform-account/**'
      - '.github/workflows/modernisation-platform-account.yml'
      - 'collaborators.json'
    branches:
      - main
  pull_request:
    paths:
      - 'terraform/modernisation-platform-account/**'
      - '.github/workflows/modernisation-platform-account.yml'
      - 'collaborators.json'
    branches:
      - main
    types: [opened, edited, reopened, synchronize]
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  TF_VAR_github_token: ${{ secrets.TERRAFORM_GITHUB_TOKEN }}
  TF_IN_AUTOMATION: true
  AWS_REGION: "eu-west-2"
  ENVIRONMENT_MANAGEMENT: ${{ secrets.MODERNISATION_PLATFORM_ENVIRONMENTS }}

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  modernisation-platform-account-plan-and-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0

      - name: Set Account Number
        run: echo "ACCOUNT_NUMBER=$(jq -r -e '.modernisation_platform_account_id' <<< $ENVIRONMENT_MANAGEMENT)" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838 # v1.7.0
        with:
          role-to-assume: "arn:aws:iam::${{ env.ACCOUNT_NUMBER }}:role/github-actions"
          role-session-name: githubactionsrolesession
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3
        with:
          terraform_version: "~1"
          terraform_wrapper: false

      - name: terraform init
        run: bash scripts/terraform-init.sh terraform/modernisation-platform-account

      - name: terraform plan
        run: bash scripts/terraform-plan.sh terraform/modernisation-platform-account

      - name: terraform apply
        if: github.event.ref == 'refs/heads/main'
        run: bash scripts/terraform-apply.sh terraform/modernisation-platform-account

      - name: Slack failure notification
        uses: 8398a7/action-slack@bdc6f9de222d3b7518e6cf99c4f3410f653cfde3 # v3.15.0
        with:
          status: ${{ job.status }}
          fields: workflow,job,repo,commit,message
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: ${{ failure() }}
