name: New member environment files

on:
  push:
    paths:
      - 'environments/**.json'
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  create-and-commit-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          path: core-repo
      - uses: actions/checkout@main
        with:
          repository: ministryofjustice/modernisation-platform-environments
          path: member-repo
      - name: Provision member environment directories
        run: bash ./core-repo/scripts/provision-member-environment-directories.sh
      # - name: Commit changes to GitHub
      #   run: bash ./scripts/git-setup.sh
      # - run: bash ./scripts/git-commit.sh terraform/environments
      # - run: bash ./scripts/git-pull-request.sh terraform/environments
      #   env:
      #     SECRET: ${{ secrets.GITHUB_TOKEN }}
