name: New environment files

on:
  push:
    paths:
      - 'environments/**.json'
      - 'environments-networks/**.json'
    branches:
      - main
  workflow_dispatch:

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  create-and-commit-files:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      - name: Provision environment directories
        run: bash ./scripts/provision-environment-directories.sh
      - name: Commit changes to GitHub
        run: bash ./scripts/git-setup.sh
      - run: bash ./scripts/git-commit.sh terraform/environments
      - run: bash ./scripts/git-pull-request.sh terraform/environments
        env:
          SECRET: ${{ secrets.GITHUB_TOKEN }}
      - uses: 8398a7/action-slack@bdc6f9de222d3b7518e6cf99c4f3410f653cfde3 # v3.15.0
        name: Slack failure notification
        with:
          status: ${{ job.status }}
          fields: workflow,job,repo,commit,message
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: ${{ failure() }}

