name: New member environment files

on:
  push:
    paths:
      - 'environments/**.json'
      - 'environments-networks/**.json'
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  create-and-commit-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          path: core-repo
      - uses: actions/checkout@v2.3.4
        with:
          repository: ministryofjustice/modernisation-platform-environments
          path: modernisation-platform-environments
          persist-credentials: false
        env:  
          TERRAFORM_GITHUB_TOKEN: ${{ secrets.TERRAFORM_GITHUB_TOKEN }}
      - name: Provision member environment directories
        run: bash ./core-repo/scripts/provision-member-directories.sh
      - name: Commit changes to GitHub
        run: bash ./core-repo/scripts/git-setup.sh ./modernisation-platform-environments
      - run: bash ./core-repo/scripts/git-commit.sh . ./modernisation-platform-environments
        env:  
          TERRAFORM_GITHUB_TOKEN: ${{ secrets.TERRAFORM_GITHUB_TOKEN }}
      - run: bash ./core-repo/scripts/git-pull-request.sh terraform/environments ./modernisation-platform-environments
        env:
          TERRAFORM_GITHUB_TOKEN: ${{ secrets.TERRAFORM_GITHUB_TOKEN }}
  create-github-environments:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Create Github member environments
        run: bash ./scripts/git-create-environments.sh
        env:
          TERRAFORM_GITHUB_TOKEN: ${{ secrets.TERRAFORM_GITHUB_TOKEN }}
