name: New member environment files

on:
  push:
#    paths:
#      - 'environments/**.json'
#   branches:
#     - feature/create-pr-in-new-repo
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  create-and-commit-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: core-repo
      - uses: actions/checkout@v2
        with:
          repository: ministryofjustice/modernisation-platform-environments
          path: modernisation-platform-environments
          persist-credentials: false
      - name: Provision member environment directories
        run: bash ./core-repo/scripts/provision-member-directories.sh
      - name: Commit changes to GitHub
        run: bash ./core-repo/scripts/git-setup.sh ./modernisation-platform-environments
      - run: bash ./core-repo/scripts/git-commit.sh terraform/environments ./modernisation-platform-environments
      - run: bash ./core-repo/scripts/git-pull-request.sh terraform/environments ./modernisation-platform-environments
        env:
          TERRAFORM_GITHUB_TOKEN: ${{ secrets.TERRAFORM_GITHUB_TOKEN }}
