name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "source/**"
      - "config/**"

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: ministryofjustice/tech-docs-github-pages-publisher:1.3
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Publish
      run: /publishing-scripts/publish.sh
    - uses: 8398a7/action-slack@v3
      name: Slack failure notification
      with:
        status: ${{ job.status }}
        fields: workflow,job,repo,commit,message
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: ${{ failure() }}
