name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "source/**"
      - "config/**"
    paths-ignore:
      - "docs/**"

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: ministryofjustice/tech-docs-github-pages-publisher:1.3
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Publish
      run: /publishing-scripts/publish.sh
