name: "Terraform: GitHub resources"

on:
  push:
    paths:
      - 'terraform/github/**'
      - './github/workflows/terraform-github.yml'
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, edited, reopened, synchronize]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  plan:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GITHUB_TOKEN: ${{ secrets.TERRAFORM_GITHUB_TOKEN }}
      TF_IN_AUTOMATION: true
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_version: 0.14.4
          terraform_wrapper: false
      - name: terraform init
        run: bash scripts/terraform-init.sh terraform/github
      - name: terraform plan
        run: bash scripts/terraform-plan.sh terraform/github
      - name: terraform apply
        if: ${{ github.event.pull_request.merged == 'true' }}
        run: bash scripts/terraform-apply.sh terraform/github
