name: "Validate core-vpc configuration"

on: 
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'scripts/tests/validate/fixtures/pre-terraform-core-vpc-validation.json'
      - 'environments-networks/**.json'

jobs:
  validate-core-vpc-config-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate core-vpc json files
        run: |
          chmod u+x scripts/tests/validate/validate-core-vpc-configuration.sh
          ./scripts/tests/validate/validate-core-vpc-configuration.sh